### ISSUE TITLE
Issue / Question? Auto Start VH server (on computer reset)

### ISSUE THREAD

**Issue by eris667** [runeberry/ValheimServerGUI#19]
Server is working, interface is good, how do I autostart the server?
My machine that is hosting the server auto-restarts daily at 1am

**Comment by dolphinspired** [comment]
Good question! Unfortunately, the answer is... you can't - yet.

But that is a good idea. Let me investigate that tonight and see what I can come up with.

**Comment by dolphinspired** [comment]
@eris667 I've started working on this, I should be able to have it tested + released in the next day or two. I've added a menu under File > Preferences that will allow you to toggle this behavior on. Here's what it will look like:

![image](https://user-images.githubusercontent.com/6467770/115133685-0de81d00-9fd8-11eb-9e81-56d82019814d.png)

**Comment by eris667** [comment]
Awesome! I created a quick Sikuli script to run until this releases -- thank you very much, this is a much better solution

**Comment by dolphinspired** [comment]
Resolved by #22

**Comment by eris667** [comment]
Installed & reset machine, worked flawlessly tyvm!
