### ISSUE TITLE
Not saving preferences, directories, server info upon exit

### ISSUE THREAD

**Issue by TheHecubus** [runeberry/ValheimServerGUI#23]
Upon restarting the GUI, I have to redirect the directories and re-enter the server info and preferences every instance.

Thank you for this program

**Comment by dolphinspired** [comment]
Hey, thanks for letting me know. The app should be saving your preferences each time you hit Start Server. If that's not working, I'll need a little more info:

1. What version of the app are you using? (you can check under Help > About)
2. What version of Windows are you running? (Windows 10 64-bit?)
3. Can you paste this path into your File Explorer and tell me what files are there, if any?
```
%USERPROFILE%\AppData\LocalLow\Runeberry\ValheimServerGUI
```

Also, start your server and then send me your application logs (Logs > change dropdown to Application) so I can see if any errors are getting logged.

**Comment by TheHecubus** [comment]
1. v 1.2.3
2. Windows 10 Pro 64-bit
3. The GUI is on my desktop. Do I need to make a folder namerd 
 "%USERPROFILE%\AppData\LocalLow\Runeberry\ValheimServerGUI"?

[App log.txt](https://github.com/runeberry/ValheimServerGUI/files/6347848/App.log.txt)

**Comment by dolphinspired** [comment]
@TheHecubus Thanks for the info! The logs revealed the problem - I changed how preferences were being saved, and forgot to make sure the folder was created first before trying to write out the file. Should be fixed in [v1.2.4](https://github.com/runeberry/ValheimServerGUI/releases/tag/v1.2.4)!

**Comment by TheHecubus** [comment]
Cool.  Thanks man.

**Comment by dolphinspired** [comment]
Resolved by 6d759e7aeaf0ce63d82a4d7f4e5b8f741646995f
