### ISSUE TITLE
Please allow the change of valheim worlds folder

### ISSUE THREAD

**Issue by r-bit-rry** [runeberry/ValheimServerGUI#25]
Valheim does support a different worlds folder (I use it as part of my configuration)
you need to pass the following (for example) as an argument:
-savedir "C:\Games\valheim_dedicated"
thanks

**Comment by dolphinspired** [comment]
@r-bit-rry Oh wow, I totally missed that option in the manual. Thanks for letting me know!

I've just published [v1.2.5](https://github.com/runeberry/ValheimServerGUI/releases) which will allow you to set that folder. Try it out and let me know if that works for you!

**Comment by r-bit-rry** [comment]
Sure, would have done the pull request myself, but I figured since its such a small fix the hassle of merging it will be greater than the work itself.
Cheers
