### ISSUE TITLE
Details on Solution Resources

### ISSUE THREAD

**Issue by micah686** [runeberry/ValheimServerGUI#34]
Can you expand on how to setup the solution resources, like `Secrets.Values.cs`? I couldn't find good documentation on how I need to configure/create them.

**Comment by dolphinspired** [comment]
Sure thing. I'd been meaning to put together some developer documentation, so I'll work on that tonight.

**Comment by dolphinspired** [comment]
@micah686 I've got two new docs to help you work on the app locally:
* [Contributing guidelines + Developer guide](https://github.com/runeberry/ValheimServerGUI/blob/main/CONTRIBUTING.md)
* [SolutionResources explanation + examples](https://github.com/runeberry/ValheimServerGUI/blob/main/SolutionResources/README.md)

Check these out and let me know if this answers your questions, or if I missed anything, etc.

**Comment by dolphinspired** [comment]
FYI, I've updated the .csproj files so that Secrets.Values.cs is no longer required when building the app in the Debug configuration.

Closing this issue, let me know if you need docs for anything else.
