### ISSUE TITLE
GUI not working

### ISSUE THREAD

**Issue by Hylum77** [runeberry/ValheimServerGUI#40]
Hi there seems to be a Startup Run Exception Error and I cant get the GUI to open.
I wanted to know if you have a fix, I sent a crash report. Thank you.

**Comment by Hylum77** [comment]
It may be a problem with the latest MS .NET 5.0.8 the GUI doesn't seem to recognize that I even have it installed (64bit Win10 version). The error above was with .NET Ver. 5.0.1. I tried updating my .NET to the latest version but now I don't even get the Error report just the message below.

![image](https://user-images.githubusercontent.com/88204771/127684762-1fcb5190-2160-419b-9261-176301d1eebe.png)

**Comment by dolphinspired** [comment]
Hey! Did you install specifically the **.NET Desktop Runtime** from [this link](https://dotnet.microsoft.com/download/dotnet/5.0)? Just the regular .NET Runtime may not contain the packages needed to run this app. If not, try installing that and let me know if the error still persists.

**Comment by Hylum77** [comment]
Hi dolphinspired, Thank you for the assistance, you were correct I needed the Desktop Runtime I had only installed the regular .NET. Everything works perfect now. Thank you for the great GUI it is exactly what I was looking for!

**Comment by dolphinspired** [comment]
Awesome, glad that worked! Feel free to hit me up if you have any more questions.
