### ISSUE TITLE
Crossplay feature addition

### ISSUE THREAD

**Issue by avenger2242** [runeberry/ValheimServerGUI#45]
Just curious if this will ever be an option for Valheim Server GUI. I have to switch back to the bat file for now to gain this feature for crossplay users. Even for PC gamepass. 
Thanks!

**Comment by avenger2242** [comment]
> Hey! Thanks for letting me know this feature was added, I haven't been following Valheim closely. I looked over the docs for crossplay, seems simple enough to add. I'm going to work on adding it this week.

Thank you for your awesome support! :D

**Comment by dolphinspired** [comment]
Hey, I took a quick pass at adding crossplay support to the GUI. Simply check "Enable Crossplay" box on the Server Controls tab. Try it out in the [v2.0.0-rc.3](https://github.com/runeberry/ValheimServerGUI/releases/tag/v2.0.0-rc.3) pre-release build. Couple of things to note:

* I gave it a quick test to make sure it works, but I noticed a couple of minor bugs. For example, the player online tracker doesn't quite work right with crossplay enabled. I'll need to investigate the new server logs to see if I can get that working again.
* I updated the application from .NET 5 to 6 for better long term support. You may already have the .NET 6 Desktop Runtime installed from a Windows update, but if not, you can download it [here](https://dotnet.microsoft.com/en-us/download/dotnet/6.0). (The GUI will prompt you to update if you don't have it installed)
* It seems like Chrome is flagging this app as a virus now? I'm investigating a fix for that, but it'll take a few days. If you run into that, try downloading it in Firefox in the meantime.

Let me know how it goes! I don't have any friends playing it on other platforms right now, so I can only test so much. Definitely let me know if you run into any new bugs.

**Comment by avenger2242** [comment]
I noticed 1.3.3 is even doing this thing with players online. Doubling sometimes tripling the same player being "online" in the list. So something has definitely changed in the server logs. Thanks for your help!

**Comment by dolphinspired** [comment]
Officially supported in v2.0.0
