### ISSUE TITLE
Directories not profile based

### ISSUE THREAD

**Issue by Minerva-BOS** [runeberry/ValheimServerGUI#54]
When I change the directories, they change for every instance. They seem to be not based on the loaded profile?

**Comment by dolphinspired** [comment]
That is how it currently works, but it could be changed. What's your use case for using separate directories per profile?

**Comment by Minerva-BOS** [comment]
I'm trying to run 2 separate servers....a "normal" modded server and a test server where I am testing different mods.

**Comment by dolphinspired** [comment]
Hey @Minerva-BOS, I've just published version 2.1.0-rc.2 [here](https://github.com/runeberry/ValheimServerGUI/releases/tag/v2.1.0-rc.2), which features the option to override paths on a per-profile basis (under the Advanced Controls tab). Try it out and let me know what you think!
