### ISSUE TITLE
my server no password use can't run because it's must set password

### ISSUE THREAD

**Issue by hisoscream** [runeberry/ValheimServerGUI#55]
my server no password need but Program must set password for run

**Comment by dolphinspired** [comment]
Hey, good catch! I just released v2.1.0-rc.1, which removes the password requirement for non-public servers. (Valheim itself will not allow you to start a public server without a password, so ValheimServerGUI doesn't either)

You can download the pre-release version [here](https://github.com/runeberry/ValheimServerGUI/releases). Let me know if that works for you, and I'll make sure this gets into the final release for 2.1 as well.
