### ISSUE TITLE
Game server connected failed

### ISSUE THREAD

**Issue by RoWEN-FCUB** [runeberry/ValheimServerGUI#56]
I'm trying to play in a private LAN, but the game does not see the created server. I'm executing the server in the same PC that I'm trying to play. Adding manually 127.0.0.1 to server list in the game does not work even. In the dedicated server console I see this error: Game server connected failed.
![32a18c43-9b57-4f15-b157-625513c110f7](https://user-images.githubusercontent.com/51714814/219738149-1b4093cf-0155-40f8-a71a-b060719b39ec.jpg)

Thanks for any help.

**Comment by dolphinspired** [comment]
@RoWEN-FCUB Did you get this figured out? I'm looking at bugs and feature requests this week, so let me know if there's anything you need help with.

**Comment by RoWEN-FCUB** [comment]
The error seems to happen when disconnected from the internet. I'm from Cuba and can not buy the game in Steam so I'm trying to play an offline craked version. Some time ago with an older version of the game I played on a LAN without Internet and no dedicated server, one PC created the game and the other just join. With the last version that's not working for me. I start the server inside the game, but when my friends try to join they a get connection error message.

Thanks for any advice.

Saludos desde Cuba.

**Comment by dolphinspired** [comment]
If you have the Crossplay option enabled, the server will route all traffic through PlayFab (a 3rd party company), so it will need to reach out to the internet. I know the server itself does some communication with Steam APIs, which might also be region-locked in your case. Hard to say.

If it happens again, try submitting a bug report from within ValheimServerGUI (under Help). This will upload some logs that I can take a closer look at. Or if that fails, copy your logs to a Pastebin and share it here. I could compare those to some logs on a working server and see if we can spot the difference.

**Comment by RoWEN-FCUB** [comment]
Many thanks for your time and answer. I will do some test following your advices.
